colo lucius

set enc=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936

set langmenu=zh_CN.UTF-8

source $VIMRUNTIME/delmenu.vim

source $VIMRUNTIME/menu.vim

language messages zh_CN.utf-8

set guifont=Consolas:h14:cANSI

syntax enable

set autoindent

set smartindent

set softtabstop=4
set shiftwidth=4
set tabstop=4
set expandtab
%retab!

set nowrap

set cursorline

set colorcolumn=81

set linebreak

set number

set showmatch

set hlsearch
set incsearch

set matchtime=5

set showmatch

set foldmethod=syntax

set foldlevel=100

set cmdheight=1

set history=1000

filetype on

filetype indent on

filetype plugin on
filetype plugin indent on

set nocp

map <F10> :NERDTreeToggle<CR>

set viminfo+=!

set iskeyword+=_,$,@,%,#,-

set linespace=0

set wildmenu

set nobackup
set noswapfile

set backspace=2

map <C-s> :w<CR>
imap <C-s> <C-o>:w<CR>

au GUIEnter * simalt ~x

set fileformat=unix

set tags=tags
set autochdir
